//Versão netBeans: 12.5
//Leandro Henrique Oliveira Neves - 2503514

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetopessoalfinal;

import static com.mycompany.projetopessoalfinal.cadAp.getCadAp;
import static com.mycompany.projetopessoalfinal.cadCliente.getCadCliente;
import static com.mycompany.projetopessoalfinal.cadFuncionarios.getCadFuncionarios;
import static com.mycompany.projetopessoalfinal.cadPersonalTrainer.getCadPersonalTrainer;
import javax.swing.JOptionPane;

public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadAcad = new javax.swing.JLabel();
        tipoCad = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        menuCad = new javax.swing.JMenu();
        cadAp = new javax.swing.JMenuItem();
        cadPessoas = new javax.swing.JMenu();
        cadCliente = new javax.swing.JMenuItem();
        cadFunc = new javax.swing.JMenuItem();
        cadPt = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        listAparelhos = new javax.swing.JMenuItem();
        listClientes = new javax.swing.JMenuItem();
        listFuncionarios = new javax.swing.JMenuItem();
        listPersonalTrainer = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cadAcad.setFont(new java.awt.Font("Sylfaen", 2, 24)); // NOI18N
        cadAcad.setText("CADASTRO ACADEMIA!");

        tipoCad.setFont(new java.awt.Font("Sitka Subheading", 2, 18)); // NOI18N
        tipoCad.setText("ESCOLHA UM TIPO PARA CADASTRAR/ANALISAR");

        menuCad.setText("Cadastro e Levantamento");

        cadAp.setText("Aparelhos");
        cadAp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadApActionPerformed(evt);
            }
        });
        menuCad.add(cadAp);

        cadPessoas.setText("Pessoas");

        cadCliente.setText("Cliente");
        cadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadClienteActionPerformed(evt);
            }
        });
        cadPessoas.add(cadCliente);

        cadFunc.setText("Funcionarios");
        cadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadFuncActionPerformed(evt);
            }
        });
        cadPessoas.add(cadFunc);

        cadPt.setText("Personal Trainer");
        cadPt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadPtActionPerformed(evt);
            }
        });
        cadPessoas.add(cadPt);

        menuCad.add(cadPessoas);

        menu.add(menuCad);

        jMenu1.setText("Relatórios");

        listAparelhos.setText("Aparelhos");
        listAparelhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listAparelhosActionPerformed(evt);
            }
        });
        jMenu1.add(listAparelhos);

        listClientes.setText("Clientes");
        listClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listClientesActionPerformed(evt);
            }
        });
        jMenu1.add(listClientes);

        listFuncionarios.setText("Funcionarios");
        listFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listFuncionariosActionPerformed(evt);
            }
        });
        jMenu1.add(listFuncionarios);

        listPersonalTrainer.setText("PersonalTrainer");
        listPersonalTrainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listPersonalTrainerActionPerformed(evt);
            }
        });
        jMenu1.add(listPersonalTrainer);

        menu.add(jMenu1);

        jMenu2.setText("Sair");

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        menu.add(jMenu2);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(tipoCad))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(cadAcad, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(cadAcad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(44, 44, 44)
                .addComponent(tipoCad)
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadApActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadApActionPerformed
        getCadAp().setVisible(true);
    }//GEN-LAST:event_cadApActionPerformed

    private void cadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadClienteActionPerformed
        getCadCliente().setVisible(true);
    }//GEN-LAST:event_cadClienteActionPerformed

    private void cadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadFuncActionPerformed
        getCadFuncionarios().setVisible(true);
    }//GEN-LAST:event_cadFuncActionPerformed

    private void listAparelhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listAparelhosActionPerformed
        listCadAp.getListCadAp().setVisible(true);
    }//GEN-LAST:event_listAparelhosActionPerformed

    private void listClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listClientesActionPerformed
        listCadCliente.getListCadCliente().setVisible(true);
    }//GEN-LAST:event_listClientesActionPerformed

    private void listFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listFuncionariosActionPerformed
        listCadFuncionario.getListCadFuncionario().setVisible(true);
    }//GEN-LAST:event_listFuncionariosActionPerformed

    private void listPersonalTrainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listPersonalTrainerActionPerformed
        listCadPersonalTrainer.getListCadPersonalTrainer().setVisible(true);
    }//GEN-LAST:event_listPersonalTrainerActionPerformed

    private void cadPtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadPtActionPerformed
        getCadPersonalTrainer().setVisible(true);
    }//GEN-LAST:event_cadPtActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        fechar();
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    public void fechar(){
        int close = JOptionPane.showConfirmDialog(
                        null,
                        "Deseja realmente sair?",
                        "Sair",
                        JOptionPane.YES_NO_OPTION
                );
        if(close == 0){
                dispose();
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cadAcad;
    private javax.swing.JMenuItem cadAp;
    private javax.swing.JMenuItem cadCliente;
    private javax.swing.JMenuItem cadFunc;
    private javax.swing.JMenu cadPessoas;
    private javax.swing.JMenuItem cadPt;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem listAparelhos;
    private javax.swing.JMenuItem listClientes;
    private javax.swing.JMenuItem listFuncionarios;
    private javax.swing.JMenuItem listPersonalTrainer;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuCad;
    private javax.swing.JLabel tipoCad;
    // End of variables declaration//GEN-END:variables
}
